### ISSUE TITLE
Port is not correctly sync

### ISSUE THREAD

**Issue by kuldeepbairwa** [leijou/php-server#29]
I have Xampp 32 bit running on my windows 10 machine .
Apache on port 80 is running on my xampp server and i have it to 80 in atom package **php-server**
and whenever i try to run it.In the chrome address bar port is replaced to 81

**Comment by ciccox** [comment]
Solved,
in windows with Xampp 32 you must specificate the ful path to PHP Executable.
In this case: C:\xampp\php\php.exe

**Comment by leijou** [comment]
This package uses PHP's built-in development server so it runs separately from apache or any other webserver.

If you have apache running then you can point its config to your development files, this package can't help with that.
If you'd like to use this package instead of configuring apache then it will work correctly on port 81 while apache continues to run on port 80
